### ISSUE TITLE
[RedbullKSU] Having Slow Web Browsing

### ISSUE THREAD

**Issue by ghost** [AnymoreProject/kernel_xiaomi_vayu#1]
I am on LineageOS 19.1 and using kiwi browser, web pages are loading so slow, reverted back to initial AnymoreKSU release, and i am not having slow web browsing issue.

**Comment by RedbullAnymore** [comment]
> I am on LineageOS 19.1 and using kiwi browser, web pages are loading so slow, reverted back to initial AnymoreKSU release, and i am not having slow web browsing issue.

wait I'll move to SFG if it's not too busy

**Comment by ghost** [comment]
It was dns issue. When i switched to other dns, it fixed my web browsing issue with Redbull.
